# Generated by Django 3.1.7 on 2021-02-24 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("terra_opp", "0003_auto_20200630_1315"),
    ]

    operations = [
        migrations.AddField(
            model_name="viewpoint",
            name="identifier",
            field=models.PositiveIntegerField(
                null=True, unique=True, verbose_name="Viewpoint number"
            ),
        ),
    ]
