# Generated by Django 3.1.7 on 2021-02-24 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("terra_opp", "0005_populate_identifier"),
    ]

    operations = [
        migrations.AlterField(
            model_name="viewpoint",
            name="identifier",
            field=models.PositiveIntegerField(
                unique=True, verbose_name="Viewpoint number"
            ),
        ),
    ]
