# Generated by Django 3.1.7 on 2021-03-03 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("terra_opp", "0006_auto_20210224_0751"),
    ]

    operations = [
        migrations.AddField(
            model_name="viewpoint",
            name="active",
            field=models.BooleanField(default=True, verbose_name="Active"),
        ),
    ]
