# Generated by Django 2.2.5 on 2019-10-09 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terra_opp', '0007_auto_20190725_1600'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='picture',
            name='remarks',
        ),
    ]
