# Generated by Django 3.2 on 2021-04-13 12:32

from django.db import migrations, models


def populate_new_identifier(apps, schema_editor):
    Picture = apps.get_model("terra_opp", "Picture")

    for picture in Picture.objects.all():
        if picture.identifier:
            picture.new_identifier = str(picture.identifier)
            picture.save()


def populate_identifier(apps, schema_editor):
    Picture = apps.get_model("terra_opp", "Picture")

    for picture in Picture.objects.all():
        if picture.new_identifier:
            picture.identifier = int(picture.new_identifier)
            picture.save()


class Migration(migrations.Migration):

    dependencies = [
        ("terra_opp", "0011_auto_20210412_1000"),
    ]

    operations = [
        migrations.AddField(
            model_name="picture",
            name="new_identifier",
            field=models.CharField(
                default="", max_length=10, verbose_name="Identifier"
            ),
        ),
        migrations.RunPython(
            code=populate_new_identifier,
            reverse_code=populate_identifier,
        ),
        migrations.RemoveField(
            model_name="picture",
            name="identifier",
        ),
        migrations.RenameField(
            model_name="picture",
            old_name="new_identifier",
            new_name="identifier",
        ),
    ]
