# Generated by Django 3.2 on 2021-04-13 10:12

from django.db import migrations


def populate_new_identifier(apps, schema_editor):
    Picture = apps.get_model("terra_opp", "Picture")

    for picture in Picture.objects.all():
        if picture.identifier:
            picture.new_identifier = str(picture.identifier)
            picture.save()


def populate_identifier(apps, schema_editor):
    Picture = apps.get_model("terra_opp", "Picture")

    for picture in Picture.objects.all():
        if picture.new_identifier:
            picture.identifier = int(picture.new_identifier)
            picture.save()


class Migration(migrations.Migration):

    dependencies = [
        ("terra_opp", "0012_picture_new_identifier"),
    ]

    operations = [migrations.RunPython(populate_new_identifier, populate_identifier)]
