# Generated by Django 3.2 on 2021-04-13 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("terra_opp", "0013_auto_20210413_1012"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="picture",
            name="identifier",
        ),
    ]
