# Generated by Django 3.2 on 2021-04-13 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("terra_opp", "0014_remove_picture_identifier"),
    ]

    operations = [
        migrations.RenameField(
            model_name="picture",
            old_name="new_identifier",
            new_name="identifier",
        ),
    ]
