# Generated by Django 3.2 on 2021-04-30 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("terra_opp", "0015_auto_20210429_0711"),
    ]

    operations = [
        migrations.AlterField(
            model_name="viewpoint",
            name="city",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="viewpoints",
                to="terra_opp.city",
            ),
        ),
    ]
